In [8]:
import numpy as np

In [11]:
vec = np.array([1,2,3])
print (vec)

[1 2 3]


In [12]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(mat.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
lst = range(5)
print(lst)

range(0, 5)


In [19]:
vec2 = np.arange(3,10)
print(vec2)

[3 4 5 6 7 8 9]


In [21]:
vec3 = np.arange(0, 14 ,3)
print(vec3)

[ 0  3  6  9 12]


In [23]:
vec4 = np.linspace(0,12,3)
print(vec4)

[ 0.  6. 12.]


In [25]:
zeromat23 = np.zeros([2,3])
print(zeromat23)


[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
vec5 = np.linspace(0,10,15)
print(vec5)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [27]:
vec5.reshape(3,5)

array([[ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286],
       [ 3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143],
       [ 7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ]])

In [29]:
print(vec5)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [30]:
vec5.reshape(5,3)

array([[ 0.        ,  0.71428571,  1.42857143],
       [ 2.14285714,  2.85714286,  3.57142857],
       [ 4.28571429,  5.        ,  5.71428571],
       [ 6.42857143,  7.14285714,  7.85714286],
       [ 8.57142857,  9.28571429, 10.        ]])

In [32]:
onesmat = np.ones([2,3])
print(onesmat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
identitymat = np.eye(5)
print(identitymat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
vec1 = np.arange(1,4)
vec2 = np.arange(3,6)
print(vec1)
print(vec2)
print(vec1+vec2)

[1 2 3]
[3 4 5]
[4 6 8]


In [38]:
print(vec1-vec2)

[-2 -2 -2]


In [39]:
print(vec1*vec2)

[ 3  8 15]


In [40]:
print(1/vec1)

[1.         0.5        0.33333333]


In [49]:
print(vec1)
print(vec2)
print(np.matmul(vec1, vec2.T))
print(np.matmul(vec2.T, vec1))
print(np.matmul(vec1, vec2))

[1 2 3]
[3 4 5]
26
26
26


In [46]:
vec3 = np.random.rand(3,3)
print(vec3)

[[0.54700605 0.01898652 0.07700384]
 [0.18624163 0.02913668 0.61809445]
 [0.43877226 0.32016531 0.77564046]]


In [48]:
print(np.matmul(vec3.T, vec2))
print(np.matmul(vec2, vec3.T))



[4.57984597 1.77433283 6.58159164]
[2.10198344 3.76574385 6.47518034]


In [50]:
samplearray = np.array([3, 4, 5, 6, 5, 4])
np.unique(samplearray)

array([3, 4, 5, 6])

In [52]:
randmat = np.random.rand(5,3)
print(randmat)

[[0.1127185  0.41958556 0.59121649]
 [0.51670694 0.54642596 0.61159574]
 [0.78061697 0.67209467 0.51891396]
 [0.51928365 0.41413303 0.42441779]
 [0.58426063 0.6330739  0.05299675]]


In [53]:
np.mean(randmat)

0.4932027022091136

In [54]:
np.max(randmat)

0.7806169695257911

In [60]:
print(randmat)
print(randmat[3:4, 1:3])
randmat[3:4, 1:3] = -500
print(randmat)

[[0.1127185  0.41958556 0.59121649]
 [0.51670694 0.54642596 0.61159574]
 [0.78061697 0.67209467 0.51891396]
 [0.51928365 0.41413303 0.42441779]
 [0.58426063 0.6330739  0.05299675]]
[[0.41413303 0.42441779]]
[[ 1.12718498e-01  4.19585558e-01  5.91216485e-01]
 [ 5.16706942e-01  5.46425965e-01  6.11595739e-01]
 [ 7.80616970e-01  6.72094675e-01  5.18913955e-01]
 [ 5.19283647e-01 -5.00000000e+02 -5.00000000e+02]
 [ 5.84260633e-01  6.33073899e-01  5.29967459e-02]]


In [62]:
submat = randmat[3:4, 1:3]
print(submat)
submat[:] = 99
print(submat)
print(randmat)

[[-500. -500.]]
[[99. 99.]]
[[1.12718498e-01 4.19585558e-01 5.91216485e-01]
 [5.16706942e-01 5.46425965e-01 6.11595739e-01]
 [7.80616970e-01 6.72094675e-01 5.18913955e-01]
 [5.19283647e-01 9.90000000e+01 9.90000000e+01]
 [5.84260633e-01 6.33073899e-01 5.29967459e-02]]


In [63]:
submat = randmat[3:4, 1:3].copy()
submat[:] = 0
print(submat)
print(randmat)

[[0. 0.]]
[[1.12718498e-01 4.19585558e-01 5.91216485e-01]
 [5.16706942e-01 5.46425965e-01 6.11595739e-01]
 [7.80616970e-01 6.72094675e-01 5.18913955e-01]
 [5.19283647e-01 9.90000000e+01 9.90000000e+01]
 [5.84260633e-01 6.33073899e-01 5.29967459e-02]]


In [66]:
randvec2 = np.random.randn(2,3)
print(randvec2)

[[-0.20915083  0.34298744 -1.01957185]
 [ 1.16092854  1.8809495  -0.02164859]]


In [67]:
randvec2 > 0

array([[False,  True, False],
       [ True,  True, False]])

In [69]:
randvec2[randvec2 < 0] = 0 

In [70]:
print(randvec2)

[[0.         0.34298744 0.        ]
 [1.16092854 1.8809495  0.        ]]


In [71]:
print(randvec2)

[[0.         0.34298744 0.        ]
 [1.16092854 1.8809495  0.        ]]


In [74]:
np.save('randvec2',randvec2)
np.savez('filezip',a = randvec2, b = randmat)

In [75]:
val = np.load('randvec2.npy')

In [76]:
print(val)

[[0.         0.34298744 0.        ]
 [1.16092854 1.8809495  0.        ]]


In [77]:
val2 = np.load('filezip.npz')

In [81]:
print(val2['a'])
print(val2['b'])

[[0.         0.34298744 0.        ]
 [1.16092854 1.8809495  0.        ]]
[[1.12718498e-01 4.19585558e-01 5.91216485e-01]
 [5.16706942e-01 5.46425965e-01 6.11595739e-01]
 [7.80616970e-01 6.72094675e-01 5.18913955e-01]
 [5.19283647e-01 9.90000000e+01 9.90000000e+01]
 [5.84260633e-01 6.33073899e-01 5.29967459e-02]]


In [84]:
np.savetxt('superfile.txt', randvec2, delimiter=',')

In [85]:
data = np.loadtxt('superfile.txt',delimiter=',')
print(data)

[[0.         0.34298744 0.        ]
 [1.16092854 1.8809495  0.        ]]
